spring:
  datasource:
    driverclassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true
jwt:
  secret: secret
